kind: Deployment
apiVersion: apps/v1
metadata:
  name: paas-agent-connector
  labels:
    app: paas-agent-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas-agent-connector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: paas-agent-connector
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: paas-agent-connector
          env:        
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: paas-agent-connector
                  key: PORT
            - name: KEY_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: paas-agent-connector
                  key: KEY_PASSPHRASE
            - name: MONGODB_CONNECT
              valueFrom:
                secretKeyRef:
                  name: paas-agent-connector
                  key: MONGODB_CONNECT
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/paas-agent-connector:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600